version: "2.1"

volumes:
  tailscale-state: {}

services:
  tailscale:
    # privileged may be optional, but requires manual step in that case
    # https://github.com/tailscale/tailscale/issues/504
    privileged: true 
    build:
      context: ./tailscale
      dockerfile: Dockerfile.template
    cap_add:
      - NET_ADMIN
    network_mode: host
    volumes:
      - tailscale-state:/tailscale
    labels:
      io.balena.features.kernel-modules: '1'

  speedtest:
    build:
      context: ./speedtest
      dockerfile: Dockerfile.template
    ports:
      - "80:8989"
